[package]
name = "ciseaux_client"
version = "0.1.0"
authors = ["TheoHay <priv.theohay@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features=["sync"] }
redis = "0.15"
futures = "0.3"
num_cpus = "1.12"